### ISSUE TITLE
Testimonials, Please!

### ISSUE THREAD

**Issue by laracasts** [laracasts/Feedback#1]
If you're a happy member of Laracasts and wouldn't mind giving me a moment of your time, I would appreciate a quick two sentence testimonial immensely! Each will be featured either on the Laracasts.com homepage, or in the testimonials section.

http://laracasts.com/testimonials

Thanks so much! :D

**Comment by TheEskil** [comment]
I just spent the last week of my three-week vacation in Thailand watching Laracasts. It's that good.

**Comment by kaidesu** [comment]
Laracast's has taught me so much, giving me the right stepping stones to climb higher to becoming a better developer. It really hits home the fact that you should never stop learning.

**Comment by J5Dev** [comment]
Laracasts is without a doubt the single greatest resource for PHP developers to emerge for an eternity, not just for the Laravel framework information, but for driving home good honest development principles!

I have, and will continue to recommend Laracasts to anyone who even mutters the letters PHP.

**Comment by zimoonline** [comment]
Learning Laravel from scratch is easy with Laracasts. Best way to learn something new is just watching Jeffery explaining in his own words.

**Comment by osbulbul** [comment]
If the others are tutorial websites, laracasts what it is ?

**Comment by rgomezcasas** [comment]
I said it a year ago and I say it again: Jeffrey is simply the teacher I never had.

**Comment by jehadassaf** [comment]
Laracasts is awesome and all – but it's the man behind it that makes all the difference.
If Jeff decides to start a tuts site about knitting, I'll be one of the first to subscribe.

**Comment by richdonne** [comment]
If cloning was legal I'd buy a jefforyway, he's changed the tutorial world inside out.

**Comment by ashwin-sureshkumar** [comment]
The best subscription for a developer ever ! Not just laravel development, Jeffrey covers programming principles, improving efficiency and workflows making development enjoyable.

**Comment by tomschlick** [comment]
Even if you're already well versed in the subject matter, the amount of ancillary knowledge you'll gain about tools, workflows, and best practices is worth the subscription in itself.

**Comment by henriquebim** [comment]
I hope I could explain why Laracasts is awesome in a way that is at least as simple to understand and complete as Laracasts videos.

**Comment by bretterer** [comment]
As an experienced Laravel developer, I have my ways of doing things.  With Laracasts, and the great way Jeffrey teaches, I learn that my way is not always the best way.  The subscription has paid for its self after the first video I watched!

**Comment by markvdputten** [comment]
As a self employed nerd working from my home office it's a challenge, though very important task, to keep myself motivated to keep learning and evolving in my profession and not to get drowned with work while repeating my own tricks. With my subscription to Laracasts I have gained a tremendous amount of knowledge in a, for me, very fun and time affordable easy way. Jeffrey is an exceptional teacher and really knows how to explain, also to non native English speakers, in vast detail what and how to get stuff done in a proper way.

**Comment by ivanvermeyen** [comment]
Laracasts tutorials are addictive! It's like an infinite well of knowledge. Whenever you think you know your stuff, Jeffrey posts another video that blows your mind!

**Comment by fuelingtheweb** [comment]
Jeffrey Way is an excellent teacher. PHP developers at any level will benefit from Laracasts. Simply the best.

**Comment by johnTurknett** [comment]
Being out of the PHP scene for a while Laracasts has helped me hit the ground running with a good mix of high level theory, every day trench work and best practices.

**Comment by fideloper** [comment]
Even when developing something I "know", I review Laracasts on the topic - there's _always_ something new Jeff talks about, even if it's just a different point of view.

**Comment by vishnupadmanabhan** [comment]
My best ever investment in education has been Laracasts . Million times better than college. Jeff, you are a Jedi knight!

**Comment by fakiolinho** [comment]
Laracasts evolved my development horizons. I am so thankful Jeff.

**Comment by rknightuk** [comment]
Laracasts taught me more in a month than it I've learnt at university in two years. Absolutely indispensable.

**Comment by jasonmccallister** [comment]
Absolutely fantastic resource for not only Laravel, but PHP principles as well. Will gladly continue to buy Jeffrey two cups of coffee a month to learn from Laracasts!

**Comment by lstables** [comment]
I spend most days checking with Laracasts, I love it, can't get enough of it and every day I learn something new.

**Comment by simonj** [comment]
Every day i check Laracasts for some new really good tutorials about Laravel! Best site ever

**Comment by adibhanna** [comment]
I've been using Laracast as my main Laravel learning resource ever since it went live. I believe it has the best Laravel teaching material out there. also, the Forum is really active, and you will find a solution/answer for any of your questions there..

**Comment by emerson-j** [comment]
Laracasts taught me how to accept payments in my projects without worrying, well worth the money.

**Comment by uxweb** [comment]
Wow Jeffrey, you and Laracasts are amazing!!. I appreciate all the time and effort you put on this stuff.

**Comment by scrubmx** [comment]
Jeffrey Way is great. I am now a Senior Developer and it wouldn't have been possible without Laracasts. I am really thankful and appreciate and recommend this website to everyone.

**Comment by tymondesigns** [comment]
Laracasts is amazing! I have learned so much from Jeffrey in the last 12 months, it has given me a much broader knowledge of PHP and software architecture. Money well spent!

**Comment by tarex** [comment]
Thanks Jeffrey , Laracasts is awesome , So many thing i've learn from here . My doa is always with you and your family . The killer feature of php is you :)  wish you all the best .

**Comment by alexsoft** [comment]
Laracasts is just perfect!! It has helped me to understand a lot of aspects of PHP and it's apps architecture. I enjoy every laracasts lesson :)

**Comment by trevorgehman** [comment]
Laracasts is an incredible value. If you're new to the Laravel community, it's the perfect place to start!

Trevor Gehman
http://getclearstream.com

**Comment by gmhenderson** [comment]
If you're new to modern PHP development Laracasts is a no-brainer. When I landed my first API project, Laracasts quickly gave me the tools I needed to understand Laravel and build a solid app. Jeffrey, made it possible for me to get a handle on a ton of new concepts in just a few months. There's nothing else like it!

**Comment by gregrobson** [comment]
With pleasure!

"For beginners through to the experienced, Laracasts helps you improve your coding skills and technique. The content and community is friendly, approachable and makes learning fun."

If you want to use this and link back, Twitter is preferred. https://twitter.com/gregrobson_UK

**Comment by ajarti** [comment]
I've been a developer for 15+ years and to date have not found a more useful learning tool than Jeffrey's Laracasts. His teaching method is unique in that it is super simple and clear, he brings across more complex architectural patterns easily and concisely.

**Comment by bart** [comment]
What Laravel became for web artisans, Laracasts became for artists making playing the PHP game an easy. Thanks a lot for your brilliant kind of explaining complex and difficult things simple!

**Comment by LespiletteMaxime** [comment]
Chuck Norris learn php on laracast !

**Comment by helioascorreia** [comment]
Laracast have the best screencast teacher, the best screencasts and until the site is on i'll always pay the subscription.

**Comment by NovaxLab** [comment]
Excelent resource for learning laravel and web development, Jeffrey is an incredible tutor!!!

**Comment by captbrogers** [comment]
Trying to figure out how and when to use repositories was giving me headaches. Laracasts made it so simple, I was able to not just understand them but put them into practice in my own project the same day.

**Comment by laracasts** [comment]
All of you are awesome. Thanks so much, and keep them coming. Over this next week, I'll add each of them to the testimonials page. 

On that note, if there's a special website url you want me to use, edit your comment with a link, and I'll use that. Otherwise, it'll just link to your GitHub profile.

**Comment by johnRivs** [comment]
Jeffrey is making my dream of making a job out of my passion for web development, a reality.

**Comment by raymondidema** [comment]
All what I can say... Put the words Laravel and Beautiful together... Jeffrey, your work @ laracasts.com is really Laraful! Thanks for your effort, way of talk and your superb approach!

**Comment by mrterryh** [comment]
Laracasts is an excellent learning platform, and not just for beginners. It can guaranteed that there's something on there that you didn't already know. And with Jeff's amazing teaching skills, you can rest assured that you're in good hands.

(It's a long one, but feel free to split it up)

**Comment by MarcTroesken** [comment]
It makes your wife jealous ! For sure :)

**Comment by alemohamad** [comment]
Not only teaches you about Laravel, but also you learn how to work through development.

**Comment by muffycompo** [comment]
After using Laravel for some time and seeing Laracasts.com, I new PHP and Laravel can be fun to learn, especially when it is being delivered by one of my mentor, Jeffrey Way whom I have looked up to since the Tutsplus/Nettuts days.
http://www.maomuffy.com

**Comment by GeoffSelby** [comment]
Laracasts is more American than apple pie! Jeff is the best instructor I've ever had the pleasure of listening to.
-- Geoff Selby

**Comment by bagwaa** [comment]
Laracast's changed the way I code, I look at web development in a totally new way now, and it's all thanks to Jeffrey's content and community contributions.

-- Richard Bagshaw

**Comment by groenewege** [comment]
Laracasts is a great replacement for looking over the shoulders of a senior developer. As a freelancer I get tremendous value from the Laracasts lessons.

**Comment by pspiteri** [comment]
If Jeffrey taught macramé, I'd want to pay him $9 a month to learn it. Thank goodness he teaches Laravel.

**Comment by tywalker** [comment]
If you want to learn to code, give Jeffrey Way your time and energy.  From beginner to advanced lessons, his style is pertinent, informative, and invaluable.

**Comment by Brunty** [comment]
I bought the subscription to Laracasts hoping to get to understand Laravel better. But not only has it done that, it's made me a better developer in all aspects of PHP.

**Comment by 5pArxz** [comment]
A long time ago, before i even knew what a statement was or how to even echo "hello world" to the browser i came across the first course from Jeffrey Way: PHP Fundamentals, and was completely blown away by the knowledge as well as teaching techniques that he possessed. It was fun and he made everything so simple to understand, it almost seemed unreal, i went from a complete developer "noob" to a professional developer within a large firm, all thanks to you. Here i am years later still learning from the exact same person. Laracasts is the best resource for any PHP Developer, and Jeffrey Way is still the best teacher! Proudly Laracasts Subscriber for life. 

--Gerhard Botha

**Comment by strebl** [comment]
Laracasts is fantastic! After each video I learned so much that I have to rewrite my app :)

**Comment by drehimself** [comment]
Before I write any code, I ask myself "What would Jeffrey do?" Odds are, he's covered it in depth on Laracasts!
[http://andremadarang.com](http://andremadarang.com)

**Comment by gregrobson** [comment]
I second @drehimself with "what would Jeffrey do?"

**Comment by edupacios** [comment]
Laracasts is great! I´ve learned a lot! But the most important thing I´ve learned is that there´s a lot left to learn, more than I thought.

**Comment by Bogardo** [comment]
Laracasts has made me a better developer in not only Laravel/PHP but in programming in general. With every screencast I've learned something new. I highly recommend it!

**Comment by elpete** [comment]
While I don't code in PHP for my current job, I always check out Laracasts for the tools and patterns that I can apply in the different languages I work in.  Worth every penny!

**Comment by ssfinney** [comment]
I'm not just a new Laravel developer, I'm a new web developer in general. Let me tell you, I wouldn't be coding anything now if it weren't for Jeffrey's excellent teaching.

**Comment by ruigomeseu** [comment]
Laracasts is THE learning resource for Laravel. I can't count how many times Jeffrey introduced me with new concepts and little tricks that save me dozens of hours over the course of the year.

If you're thinking about signing up, just do it! It's definitely worth it.

https://ruigomes.me

**Comment by neutronstein** [comment]
Simply AMAZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIING !!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by kyleferguson** [comment]
If Heisenberg cooked screencasts, this would be his cookbook.

**Comment by freekmurze** [comment]
A Laracast a day keeps the bad practices away

**Comment by Jamesking56** [comment]
Laracasts has taught me more than I could've ever learned on my own. Jeffrey's teachings have enabled me to accelerate my learning with the framework and land me my first Laravel full-time job at a company who now regard me as their "Laravel expert". Laracasts has been the best resource I ever invested money into and it's worth every single penny!

www.Jamesking56.co.uk
@Jamesking56 (Twitter)

**Comment by rudowastaken** [comment]
When I watch most of new episodes even before email of them being released reaches my mailbox, that's the excitement no other code learning source can compete with. 

Laracasts are _way_ better than Game of Thrones! #yesIWentThere

**Comment by dwoodard** [comment]
Jeffery Way IS that ternary machine that can run any algorithm.  You learn to just except his his infinite awesomeness, because it just hurts your head to think about it too much!
![bn8yuhocaaa0pcf](https://cloud.githubusercontent.com/assets/77433/3650782/a6cb078e-111f-11e4-8964-5ea6ae1e91be.jpg)

**Comment by antoniofrignani** [comment]
Apart from some sporadic Justin Bieber appearance on the site, you made learning even advanced topics a cinch. It is true that it is like Netflix for developers, but sometimes it is as addictive (even most) as Youporn! :sunglasses:

**Comment by kojuka** [comment]
Best training we've had hands down.  Great teaching style and a thoughtful mix of some easy newbie friendly code with some advanced ninja code concepts.  Its the full range which is great for our developers.

**Comment by cpriego** [comment]
I graduated college knowing a little bit of everything: from the various programming languages like C and Java to the different programming paradigms like spaghetti, procedural, Object Oriented and Functional. I learned that you have to follow standards and best practices whenever you could for they allow for easier code understanding and maintainability, however, learning a new language is like being the new kid in town, you know you need to go to the supermarket to buy your food but you don't know where the closest supermarket is nor the best route to get there.

Jeffrey is that good neighbor willing to help you, guide you and teach you those little tips and tricks that make your "new life" just so easy. He covers EVERY topic in the most delightful way and makes learning those tricky concepts that make painting a Mona Lisa with a paintball gun with your eyes closed while ridding a rodeo bull look like an easy task become a walk in the park.

For a practical learner that finds it very hard to learn only from books, being able to "see" what a design pattern or dependency injection really is has truly paid off. 

The best investment I've ever done in my life.

If you're still hesitating take a quick look to the free lessons. Rest assured, you won't regret it.

**Comment by rawrstack** [comment]
i subscribe for a month laracast. so far so good. never stop learning.. i learn a lot. As a student, i wish got coupon code for us to subscribe for a year at least.

**Comment by nicolasmuneram** [comment]
I've always preferred learning programming languages with online courses and videos, well, let me tell you, that from all videos I've seen, from all the University classes I've taken, I have never seen a better instructor than Jeffrey. You actually get attached to his screencasts like you would to a TV Show!

**Comment by sahibalejandro** [comment]
All the knowledge that Jeffrey shares with us, is simply invaluable!

**Comment by saifdev** [comment]
I am so much impress by what you do that I do not find the words, you share with us all your knowledge on LARAVEL, me and all the LARAVEL community thank you for your efforts, which makes LARACASTS exceptional these the choices of tutorials, quality and much more..., on this moment what makes LARAVEL exceptional is YOU!!!

Jeffrey THE LARAVEL KILLER MACHINE.

**Comment by dammyammy** [comment]
Learning has never been this fun... Jeffrey is by far the best teacher I've ever had. He Makes learning Laravel as easy as ABC.

**Comment by CaporalDead** [comment]
Excellent video, excellent examples, nothing to say except: very well done Jeff, you're amazing;) I never Regrete my monthly subscription since I registered :).

**Comment by rockymontana** [comment]
Jeffreys ten minutes of pedagogic instructions has taken me to the next level in web development. 
It's an amazing site packed with aha moments.

**Comment by jmverges** [comment]
Hi there, 
I'm quite happy with Laravel and Laracast. However while I'm seeing Laravel 5 Fundamentals I could see here: https://laracasts.com/series/laravel-5-fundamentals/episodes/15?autoplay=true something wrong. 
I just cloned Laravel repository and this episode is showing a few folders and files that are not included by default like views/auth/ , Services\Registrar and https://github.com/laravel/laravel/blob/master/app/Http/routes.php has not the default code showed in the video. 
Let me know what I'm missing and thank you for the amazing work.
